map_type: "vlmap" # "vlmap", "gt", "clip", "clip_gradcam", "vlmaps_lseg_3d"
pose_info:
  pose_type: camera_base # mobile_base, camera_base
  rot_type: "quat" # "mat", or "quat" (x, y, z, w)
  # if pose_type is camera, the following parameters are ignored
  camera_height: 1.5
  base2cam_rot: [1, 0, 0, 0, -1, 0, 0, 0, -1]
  base_forward_axis: [0, 0, -1]
  base_left_axis: [-1, 0, 0]
  base_up_axis: [0, 1, 0]
skip_frame: 1
cam_calib_mat: [570.1754150390625, 0.0, 319.5, 0.0, 570.1754150390625, 239.5, 0.0, 0.0, 1.0]
grid_size: ${params.gs}
cell_size: ${params.cs}
max_depth: ${params.max_depth}
min_depth: ${params.min_depth}
depth_sample_rate: 1000
dilate_iter: 3 # TODO: Tune?
gaussian_sigma: 1.0 # TODO: Tune?
customize_obstacle_map: False
potential_obstacle_names:
  - "chair"
  - "wall"
  - "wall above the door"
  - "table"
  - "window"
  - "floor"
  - "stairs"
  - "other"
obstacle_names:
  - "wall"
  - "chair"
  - "table"
  - "window"
  - "stairs"
  - "other"
categories: "mp3d" # "mp3d", "ai2thor"
